# Buckets, image registry and the metrics warehouse.

# ---------------------------------------------------------------------------------------
# Data buckets
# ---------------------------------------------------------------------------------------

# Split into three buckets rather than one with prefixes, because they have genuinely
# different lifecycles:
#
#   raw       ~3.3 GB, downloaded once, never regenerated -- versioning ON, never expire
#   derived   ~12 GB, regenerated by the pipeline -- versioning OFF, cheap to rebuild
#   artifacts small, the outputs we actually care about -- versioning ON, never expire
#
# One bucket with one lifecycle policy would either over-protect the derived data (paying to
# version 12 GB that a pipeline run can recreate) or under-protect the raw data.

resource "google_storage_bucket" "raw" {
  name                        = "${var.project_id}-raw"
  location                    = var.region
  uniform_bucket_level_access = true
  force_destroy               = false # a 3.1 GB genome download is slow to repeat

  versioning { enabled = true }

  depends_on = [google_project_service.apis]
}

resource "google_storage_bucket" "derived" {
  name                        = "${var.project_id}-derived"
  location                    = var.region
  uniform_bucket_level_access = true
  force_destroy               = true # regenerable by definition

  # Old pipeline outputs are not worth storing. 90 days is long enough to compare against a
  # previous run and short enough that abandoned experiments stop costing money.
  lifecycle_rule {
    condition { age = 90 }
    action { type = "Delete" }
  }

  depends_on = [google_project_service.apis]
}

resource "google_storage_bucket" "artifacts" {
  name                        = "${var.project_id}-artifacts"
  location                    = var.region
  uniform_bucket_level_access = true
  force_destroy               = false

  versioning { enabled = true }

  depends_on = [google_project_service.apis]
}

# Terraform's own state, once it exists. Chicken-and-egg: this bucket is created by the
# local backend, then `terraform init -migrate-state` moves state into it.
resource "google_storage_bucket" "tfstate" {
  name                        = "${var.project_id}-tfstate"
  location                    = var.region
  uniform_bucket_level_access = true
  force_destroy               = false

  versioning { enabled = true } # state history is the recovery path for a bad apply

  depends_on = [google_project_service.apis]
}

# ---------------------------------------------------------------------------------------
# Container images
# ---------------------------------------------------------------------------------------

resource "google_artifact_registry_repository" "images" {
  location      = var.region
  repository_id = "rbp"
  format        = "DOCKER"
  description   = "CPU and GPU images for the RBP pipeline"

  # Keep the last 5 of each image. Without this, every build accumulates and the registry
  # bill grows forever for images nobody will run again.
  cleanup_policies {
    id     = "keep-recent"
    action = "KEEP"
    most_recent_versions { keep_count = 5 }
  }

  depends_on = [google_project_service.apis]
}

# ---------------------------------------------------------------------------------------
# Metrics warehouse
# ---------------------------------------------------------------------------------------

# 9,350 training runs x ~40 columns. As CSVs in a bucket this is unqueryable; in BigQuery
# it is a SQL question. Under 10 GB and with our query volume it is inside the free tier.
resource "google_bigquery_dataset" "metrics" {
  dataset_id                 = "rbp_metrics"
  location                   = var.bq_location
  description                = "Per-run metrics from the sweep, and analysis outputs"
  delete_contents_on_destroy = true

  depends_on = [google_project_service.apis]
}

resource "google_bigquery_table" "runs" {
  dataset_id          = google_bigquery_dataset.metrics.dataset_id
  table_id            = "runs"
  deletion_protection = false

  # Partitioned by run date and clustered on the columns we filter by constantly, so a query
  # for "all SpliceBERT results on the dinuc arm" scans a fraction of the table.
  time_partitioning {
    type  = "DAY"
    field = "started_at"
  }
  clustering = ["architecture", "negative_arm", "cell_line"]

  schema = jsonencode([
    { name = "run_id", type = "STRING", mode = "REQUIRED" },
    { name = "started_at", type = "TIMESTAMP", mode = "REQUIRED" },
    { name = "protein", type = "STRING", mode = "REQUIRED" },
    { name = "cell_line", type = "STRING", mode = "REQUIRED" },
    { name = "negative_arm", type = "STRING", mode = "REQUIRED" }, # gc | dinuc
    { name = "architecture", type = "STRING", mode = "REQUIRED" },
    { name = "fold", type = "INTEGER", mode = "REQUIRED" },
    { name = "seed", type = "INTEGER", mode = "REQUIRED" },
    { name = "n_train", type = "INTEGER" },
    { name = "n_val", type = "INTEGER" },
    { name = "n_test", type = "INTEGER" },
    { name = "epochs_run", type = "INTEGER" },
    { name = "best_epoch", type = "INTEGER" },
    { name = "val_auroc", type = "FLOAT" },
    { name = "test_auroc", type = "FLOAT" },
    { name = "test_auprc", type = "FLOAT" },
    { name = "params_total", type = "INTEGER" },
    { name = "params_trainable", type = "INTEGER" },
    { name = "seconds", type = "FLOAT" },
    { name = "gpu_type", type = "STRING" },
    { name = "preempted_count", type = "INTEGER" },
    { name = "scores_uri", type = "STRING" }, # per-row out-of-fold scores in GCS
    { name = "dataset_hash", type = "STRING" },
    { name = "image_digest", type = "STRING" },
    { name = "git_sha", type = "STRING" },
  ])
}
