"""F5: how does this literature actually construct negatives, and does it report a baseline?

    python scripts/negative_set_survey.py

The paper's recommendation is to report the composition-only AUROC obtained under the same
protocol alongside every headline AUROC. That recommendation is worth making only if the field
does not already do it, and worth aiming at the right target only if we know what the field
actually does. Both were assumed here until this survey; one of the assumptions was wrong.

THE ENTRIES ARE HAND-CURATED FROM PRIMARY SOURCES, and each carries the sentence it was read
from so a reader can check it rather than trust it. A literature survey has no committed table
upstream of it, so the quote IS the evidence and it is stored beside the classification. Where a
paper offers several constructions, the one used for its own reported benchmarks is recorded and
the alternative is noted.

WHAT IT CORRECTED. This paper's own shuffled-arm section claimed that dinucleotide-preserving
shuffling is "what most published predictors use" and named GraphProt, iDeepS and RBPsuite. That
is wrong twice over. GraphProt shuffles genomic COORDINATES within bound genes, not sequence;
the RBP-24 dataset behind iDeepS does the same with BedTools; RBPsuite 2.0 uses pybedtools
shuffle to non-peak regions of the same transcript. Sequence-level dinucleotide shuffling appears
only as an option for FASTA input in RNAProt and as an alternative in DeepCLIP. The dominant
construction in this literature is POSITIONAL, and it leaves composition entirely free, which is
a stronger motivation for reporting the baseline than the one the section originally gave.
"""

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
TABLES = ROOT / "results" / "tables"

# kind: "coordinate" = shuffle or sample genomic intervals; "other_rbp" = bias-aware;
# "sequence_shuffle" = permute the positive's own sequence.
SURVEY = [
    dict(method="GraphProt", year=2014, kind="coordinate", composition_baseline=False,
         url="https://pmc.ncbi.nlm.nih.gov/articles/PMC4053806/",
         quote="we created a set of unbound sites by shuffling the coordinates of bound sites "
               "within all genes occupied by at least one binding site"),
    dict(method="RBP-24 dataset (iDeepS, iDeepE, deepRAM)", year=2018, kind="coordinate",
         composition_baseline=False,
         url="https://link.springer.com/article/10.1186/s12864-018-4889-1",
         quote="negative sites generated by shuffling the coordinates of at least one binding "
               "site in all genes using BedTools"),
    dict(method="pysster", year=2018, kind="other_rbp", composition_baseline=False,
         url="https://academic.oup.com/bioinformatics/article/34/17/3035/4962494",
         quote="one half sampled uniformly from regions with no overlapping binding sites of "
               "the given RBP and the other half sampled from binding sites of other RBPs"),
    dict(method="DeepCLIP", year=2020, kind="coordinate", composition_baseline=False,
         url="https://academic.oup.com/nar/article/48/13/7099/5859960",
         quote="randomly placing each within the same gene as the corresponding positive "
               "binding site such that no background regions overlap either a positive binding "
               "site or another background region; scrambling offered as an alternative"),
    dict(method="RNAProt", year=2021, kind="coordinate", composition_baseline=False,
         url="https://pmc.ncbi.nlm.nih.gov/articles/PMC8372218/",
         quote="selected randomly from gene or transcript regions containing positive sites; "
               "k-nucleotide shuffling is offered only for FASTA input"),
    dict(method="Horlacher et al. benchmark (37 methods compiled, 11 run)", year=2023,
         kind="other_rbp", composition_baseline=False,
         url="https://www.biorxiv.org/content/10.1101/2023.02.14.528560v1.full",
         quote="negative-1 uniformly sampling positions from transcripts overlapping with at "
               "least one binding site; negative-2 sampling from binding sites of other RBPs"),
    dict(method="RBPsuite 2.0", year=2025, kind="coordinate", composition_baseline=False,
         url="https://pmc.ncbi.nlm.nih.gov/articles/PMC11899677/",
         quote="Negative RBP binding regions were produced by implementing a shuffle of "
               "pybedtools, these negative sites are those regions without any identified "
               "binding peak located within the same transcript"),
]


def log(m):
    print(m, flush=True)


def main():
    t = pd.DataFrame(SURVEY)
    if t.quote.str.len().min() < 20 or t.url.str.startswith("http").sum() != len(t):
        sys.exit("every entry needs a source URL and the sentence it was read from")
    t.to_csv(TABLES / "negative_set_survey_per_method.csv", index=False)

    out = []
    n = len(t)
    log(f"\n=== F5: negative-set construction in {n} widely used methods and benchmarks ===\n")
    log(f"  {'method':46s} {'year':>5s} {'construction':>16s} {'comp. baseline':>15s}")
    for r in t.itertuples():
        log(f"  {r.method:46s} {r.year:5d} {r.kind:>16s} "
            f"{'yes' if r.composition_baseline else 'NO':>15s}")

    out.append({"check": "methods and benchmarks surveyed", "value": n, "n": n})
    for kind in sorted(t.kind.unique()):
        out.append({"check": f"methods whose negatives are {kind}",
                    "value": int((t.kind == kind).sum()), "n": n})

    # THE NUMBER THE RECOMMENDATION RESTS ON. If the field already reported a composition-only
    # AUROC beside its headline, this paper would be recommending current practice.
    n_base = int(t.composition_baseline.sum())
    out.append({"check": "surveyed sources reporting a composition-only baseline",
                "value": n_base, "n": n})
    log(f"\n  {n_base} of {n} report a composition-only AUROC beside their headline.")

    # AND THE CORRECTION THIS SURVEY FORCED. Sequence-level dinucleotide shuffling is NOT the
    # dominant construction; interval shuffling is, and it leaves composition entirely free.
    n_seq = int((t.kind == "sequence_shuffle").sum())
    n_coord = int((t.kind == "coordinate").sum())
    out.append({"check": "surveyed sources whose negatives permute the positive's own sequence",
                "value": n_seq, "n": n,
                "note": "the construction this paper's shuffled arm implements"})
    out.append({"check": "surveyed sources whose negatives are relocated genomic intervals",
                "value": n_coord, "n": n})
    log(f"  {n_coord} of {n} relocate genomic intervals and {n_seq} of {n} permute the "
        f"positive's own sequence.")
    log("  So the dominant construction is POSITIONAL and leaves composition free, which is why")
    log("  the composition baseline varies across protocols at all, and is a stronger reason to")
    log("  report it than the claim this paper originally made about shuffling.")

    pd.DataFrame(out).to_csv(TABLES / "negative_set_survey.csv", index=False)
    log("\nwrote negative_set_survey.csv and negative_set_survey_per_method.csv")


if __name__ == "__main__":
    main()
