"""Typeset Supplementary Table S1 from its CSV, so the supplement is self-contained.

    python scripts/table_s1_tex.py            # writes manuscript/sections/table_s1.tex

Why this exists. The supplement used to say "the file supplementary_table_s1.csv ships with this
document" and print nothing else, so Table S1 was a pointer. That is three files to upload
instead of two, and a reader who opens only the PDF gets a reference to something they do not
have. bioRxiv takes supplementary files separately and nothing makes a reader fetch them.

The CSV stays: it is the machine-readable form and the columns a reuser wants, including the
per-arm baselines and contributions, are wider than a page. What is typeset here is what the
caption already promised, the accession mapping, so the PDF answers "which ENCODE experiment is
this dataset?" on its own.

Generated rather than hand-written, and gated. A hand-copied table of 95 rows is a table that
goes stale the first time the panel changes and nobody notices, which is this repository's most
frequent defect by a wide margin. build.sh runs this before pdflatex, so the typeset rows cannot
disagree with the CSV they came from.
"""

import csv
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "results" / "tables" / "supplementary_table_s1.csv"
OUT = ROOT / "manuscript" / "sections" / "table_s1.tex"

# The caption's promise, in order. The comp_* and gain_* columns stay in the CSV only: six more
# numeric columns do not fit a portrait page and are not what this table is for.
COLS = [("protein", "protein", "l"), ("cell", "cell line", "l"),
        ("accession", "ENCFF file", "l"), ("experiment", "ENCSR experiment", "l"),
        ("n_replicates", "reps", "r"), ("pairs", "pairs", "r"),
        ("in_three_arm_panel", "3 arms", "c")]


def esc(s):
    return s.replace("_", r"\_").replace("&", r"\&").replace("%", r"\%")


def main():
    if not SRC.exists():
        sys.exit(f"missing {SRC}")
    rows = list(csv.DictReader(SRC.open(newline="")))
    if not rows:
        sys.exit("supplementary_table_s1.csv has no rows; refusing to write an empty table")
    missing = [c for c, _, _ in COLS if c not in rows[0]]
    if missing:
        sys.exit(f"supplementary_table_s1.csv has no {missing}; the table cannot be built")

    align = "".join(a for _, _, a in COLS)
    head = " & ".join(rf"\textbf{{{esc(h)}}}" for _, h, _ in COLS) + r" \\"
    body = []
    for r in sorted(rows, key=lambda x: x["dataset"]):
        cells = []
        for c, _, _ in COLS:
            v = (r[c] or "").strip()
            if c == "in_three_arm_panel":
                v = "yes" if v.lower() == "true" else "no"
            elif c == "pairs" and v.isdigit():
                v = f"{int(v):,}".replace(",", r"{,}")
            cells.append(esc(v))
        body.append(" & ".join(cells) + r" \\")

    n_panel = sum(1 for r in rows if (r["in_three_arm_panel"] or "").lower() == "true")
    OUT.write_text(
        "% GENERATED by scripts/table_s1_tex.py from results/tables/supplementary_table_s1.csv.\n"
        "% Do not edit: build.sh regenerates it, so an edit here is silently discarded.\n"
        rf"\begin{{longtable}}{{{align}}}" "\n"
        r"\caption{\textbf{Dataset to ENCODE accession.} All " f"{len(rows)}"
        r" datasets in the candidate panel, one row each, with the ENCODE file and experiment"
        r" accessions needed to retrieve the source peaks. \textbf{3 arms} is whether the"
        r" dataset carries all three negative-set protocols; the " f"{len(rows) - n_panel}"
        r" marked \textit{no} cleared the minimum-pair floor under dinucleotide matching but"
        r" not under GC matching, which is the difference between the " f"{len(rows)}"
        r" selected datasets and the " f"{n_panel}"
        r" the study reports on. The same table with each arm's composition baseline and"
        r" contribution is \texttt{supplementary\_table\_s1.csv}, which ships beside this"
        r" document.}\label{tab:s1}\\" "\n"
        r"\toprule" "\n" + head + "\n" r"\midrule" "\n" r"\endfirsthead" "\n"
        r"\multicolumn{" f"{len(COLS)}" r"}{l}{\textit{Table S1, continued}}\\" "\n"
        r"\toprule" "\n" + head + "\n" r"\midrule" "\n" r"\endhead" "\n"
        r"\midrule\multicolumn{" f"{len(COLS)}" r"}{r}{\textit{continued on the next page}}\\"
        "\n" r"\endfoot" "\n" r"\bottomrule" "\n" r"\endlastfoot" "\n"
        + "\n".join(body) + "\n" r"\end{longtable}" "\n")
    print(f"  wrote {OUT.relative_to(ROOT)}: {len(rows)} rows, {n_panel} in the three-arm panel")


if __name__ == "__main__":
    main()
